/ improving pipeline

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -72,17 +72,16 @@ jobs:
         run: |
           docker run --rm -v "${PWD}":/project bash:latest chown --recursive $(id -u):$(id -g) /project
 
-      - name: Build the documentation and PDF
+      - name: Build the html documentation and PDF
         run: |
-          # Build HTML docs
-          docker run --rm \
+          
+           docker run --rm \
             -u "$(id -u):$(id -g)" \
             -v "${PWD}:/docs" \
             -w /docs \
             squidfunk/mkdocs-material \
-            build -d /docs/build/site
+            build -d /docs/build/site \
           
-          # Build PDF
           docker run --rm \
             -v "${PWD}:/data" \
             -w /data \
@@ -97,7 +96,7 @@ jobs:
               -o build/site/documentation.pdf
           
           # Validierungen
-          test -f build/site/index.html || (echo "MkDocs output missing!" && exit 1)
+          test -f build/site/doc/index.html || (echo "MkDocs output missing!" && exit 1)
           test -f build/site/documentation.pdf || (echo "PDF output missing!" && exit 1)
 
       - name: Build & push documentation image
